/* The following code was generated by JFlex 1.4.3 on 20/02/21 14:08 */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 20/02/21 14:08 from the specification file
 * <tt>D:/ah/ifce/topicos java web/project7/AnalisadorLexico/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\15\1\10\2\0\1\15\22\0\1\15\1\55\1\6\2\0"+
    "\1\52\1\56\1\4\1\61\1\62\1\11\1\50\1\15\1\51\1\3"+
    "\1\7\12\2\1\0\1\5\1\54\1\47\1\53\2\0\22\12\1\31"+
    "\7\12\1\13\1\0\1\14\1\52\1\1\1\0\1\24\1\27\1\35"+
    "\1\25\1\30\1\21\1\33\1\36\1\16\1\12\1\42\1\22\1\44"+
    "\1\17\1\23\1\43\1\12\1\32\1\37\1\20\1\26\1\40\1\41"+
    "\1\46\1\34\1\45\1\63\1\57\1\63\1\60\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\5\22\2\5\5\1\1\1\5\1\1\1\5\1\4"+
    "\6\0\1\2\1\7\13\2\1\7\27\2\1\0\3\3"+
    "\1\10\2\0\1\11\1\7\44\2\2\0\1\11\1\0"+
    "\27\2\1\3\1\10\1\0\4\2\1\7\43\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\64\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8"+
    "\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478"+
    "\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618"+
    "\0\u064c\0\u057c\0\u0680\0\u06b4\0\64\0\u06e8\0\u071c\0\u0750"+
    "\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u01d4\0\u0888\0\u08bc"+
    "\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0a5c"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc"+
    "\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\u0d9c"+
    "\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c"+
    "\0\u0f70\0\u0fa4\0\u071c\0\u0750\0\u0784\0\u07b8\0\u0fd8\0\u100c"+
    "\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178\0\u11ac"+
    "\0\u11e0\0\u1214\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u1318\0\u134c"+
    "\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u1450\0\u1484\0\u14b8\0\u14ec"+
    "\0\u1520\0\u1554\0\u1588\0\u15bc\0\u15f0\0\u1624\0\u1658\0\u168c"+
    "\0\u16c0\0\u16f4\0\u1728\0\u175c\0\u1790\0\u17c4\0\u17f8\0\u182c"+
    "\0\u1860\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964\0\u1998\0\u19cc"+
    "\0\u1a00\0\u1a34\0\u1a68\0\u1a9c\0\u1ad0\0\u1b04\0\u1b38\0\u1b6c"+
    "\0\u1ba0\0\u1bd4\0\u1c08\0\u1c3c\0\u1c70\0\u1ca4\0\u1cd8\0\u1d0c"+
    "\0\u1d40\0\64\0\u0fd8\0\u1d74\0\u1da8\0\u1ddc\0\u1e10\0\u1e44"+
    "\0\u1178\0\u1e78\0\u1eac\0\u1ee0\0\u1f14\0\u1f48\0\u1f7c\0\u1fb0"+
    "\0\u1fe4\0\u2018\0\u204c\0\u2080\0\u20b4\0\u20e8\0\u211c\0\u2150"+
    "\0\u2184\0\u21b8\0\u21ec\0\u2220\0\u2254\0\u2288\0\u22bc\0\u22f0"+
    "\0\u2324\0\u2358\0\u238c\0\u23c0\0\u23f4\0\u2428\0\u245c\0\u2490"+
    "\0\u24c4\0\u24f8\0\u252c\0\u2560";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\11\1\12\1\13\2\5\1\11\1\14\1\15\1\16"+
    "\1\17\1\20\1\13\1\21\1\22\1\13\1\23\1\24"+
    "\1\25\1\26\1\27\1\13\1\30\1\13\1\31\1\32"+
    "\1\33\1\13\1\34\3\13\1\35\1\36\1\37\1\35"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\2\5"+
    "\65\0\2\3\7\0\1\3\3\0\31\3\17\0\1\4"+
    "\1\47\60\0\5\50\1\0\56\50\5\51\1\0\56\51"+
    "\7\0\1\52\1\0\1\53\35\0\1\45\24\0\1\11"+
    "\4\0\1\11\57\0\1\45\35\0\1\45\15\0\2\3"+
    "\7\0\1\13\1\54\2\0\31\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\1\13\1\55\1\13\1\56\22\13"+
    "\1\57\2\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\6\13\1\60\3\13\1\61\16\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\14\13\1\62\3\13\1\63\10\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\1\64\3\13"+
    "\1\65\1\66\23\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\5\13\1\67\23\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\11\13\1\70\7\13\1\71\7\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\5\13\1\72\4\13"+
    "\1\73\16\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\5\13\1\74\6\13\1\75\1\13\1\76\12\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\1\13\1\77\2\13"+
    "\1\100\23\13\1\101\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\2\13\1\102\26\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\12\13\1\103\16\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\5\13\1\104\23\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\4\13\1\105\1\106\1\100"+
    "\11\13\1\107\10\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\2\13\1\110\5\13\1\111\5\13\1\112\1\13"+
    "\1\113\2\13\1\114\5\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\5\13\1\115\23\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\20\13\1\116\10\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\6\13\1\117\1\13\1\120"+
    "\3\13\1\121\14\13\64\0\1\45\63\0\2\45\62\0"+
    "\1\45\1\0\1\45\61\0\1\45\3\0\1\45\57\0"+
    "\1\45\4\0\1\45\65\0\1\45\64\0\1\45\55\0"+
    "\1\122\14\0\1\123\61\0\4\50\1\124\1\0\56\50"+
    "\5\51\1\0\1\125\55\51\10\126\1\0\53\126\64\127"+
    "\2\0\1\130\11\0\1\131\50\0\2\3\7\0\1\13"+
    "\1\54\2\0\2\13\1\132\16\13\1\133\7\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\25\13\1\134\3\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\2\13\1\135"+
    "\26\13\16\0\2\3\7\0\1\13\1\54\2\0\23\13"+
    "\1\56\5\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\6\13\1\136\22\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\1\137\13\13\1\140\14\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\1\13\1\141\27\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\5\13\1\142\23\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\14\13\1\56\14\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\1\13\1\143"+
    "\27\13\16\0\2\3\7\0\1\13\1\54\2\0\21\13"+
    "\1\144\7\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\21\13\1\145\7\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\10\13\1\146\20\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\3\13\1\147\25\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\5\13\1\150\23\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\12\13\1\151\16\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\2\13\1\152\26\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\10\13\1\153"+
    "\20\13\16\0\2\3\7\0\1\13\1\54\2\0\21\13"+
    "\1\152\7\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\2\13\1\154\26\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\14\13\1\155\14\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\2\13\1\156\26\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\2\13\1\157\26\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\6\13\1\160\22\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\1\13\1\161\27\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\6\13\1\66"+
    "\22\13\16\0\2\3\7\0\1\13\1\54\2\0\6\13"+
    "\1\162\5\13\1\163\14\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\25\13\1\164\3\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\1\13\1\165\27\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\5\13\1\166\23\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\1\167\30\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\1\170\3\13\1\171"+
    "\24\13\16\0\2\3\7\0\1\13\1\54\2\0\1\172"+
    "\30\13\16\0\2\3\7\0\1\13\1\54\2\0\17\13"+
    "\1\173\11\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\11\13\1\174\17\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\1\175\4\13\1\176\23\13\17\0\1\177\61\0"+
    "\11\127\1\200\52\127\2\0\1\130\11\0\1\201\62\0"+
    "\1\202\51\0\2\3\7\0\1\13\1\54\2\0\12\13"+
    "\1\203\16\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\2\13\1\204\26\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\4\13\1\205\1\166\23\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\1\206\30\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\1\13\1\207\27\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\21\13\1\56\7\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\5\13\1\210\23\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\6\13\1\211"+
    "\22\13\16\0\2\3\7\0\1\13\1\54\2\0\6\13"+
    "\1\212\22\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\15\13\1\56\13\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\2\13\1\213\26\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\12\13\1\166\16\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\11\13\1\172\17\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\6\13\1\214\22\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\4\13\1\215\24\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\6\13\1\216"+
    "\22\13\16\0\2\3\7\0\1\13\1\54\2\0\12\13"+
    "\1\56\16\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\26\13\1\56\2\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\12\13\1\217\16\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\1\67\30\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\10\13\1\220\20\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\5\13\1\56\23\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\21\13\1\137\7\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\2\13\1\221\16\13"+
    "\1\212\7\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\2\13\1\222\26\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\1\223\30\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\12\13\1\66\16\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\17\13\1\224\11\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\14\13\1\212\14\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\2\13\1\225\26\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\7\13\1\56\21\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\6\13\1\226"+
    "\22\13\16\0\2\3\7\0\1\13\1\54\2\0\4\13"+
    "\1\152\24\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\24\13\1\227\4\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\4\13\1\222\24\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\22\13\1\230\6\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\2\13\1\231\26\13\17\0\1\177"+
    "\57\0\1\232\1\0\7\127\1\233\1\127\1\200\52\127"+
    "\13\0\1\234\64\0\1\131\50\0\2\3\7\0\1\13"+
    "\1\54\2\0\14\13\1\235\14\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\6\13\1\236\22\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\12\13\1\237\16\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\22\13\1\152\6\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\21\13\1\240"+
    "\7\13\16\0\2\3\7\0\1\13\1\54\2\0\23\13"+
    "\1\241\5\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\4\13\1\242\24\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\2\13\1\56\26\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\14\13\1\243\14\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\10\13\1\244\20\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\12\13\1\245\16\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\24\13\1\56\4\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\1\13\1\246"+
    "\27\13\16\0\2\3\7\0\1\13\1\54\2\0\14\13"+
    "\1\247\14\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\1\250\30\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\1\251\30\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\17\13\1\252\11\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\20\13\1\253\10\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\17\13\1\254\11\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\2\13\1\116\26\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\6\13\1\255\22\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\6\13\1\76\22\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\12\13\1\256"+
    "\16\13\17\0\1\130\62\0\2\3\7\0\1\13\1\54"+
    "\2\0\3\13\1\257\25\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\1\13\1\260\27\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\26\13\1\261\2\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\1\262\30\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\4\13\1\263\24\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\6\13\1\264\22\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\4\13\1\212"+
    "\24\13\16\0\2\3\7\0\1\13\1\54\2\0\6\13"+
    "\1\247\22\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\7\13\1\137\21\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\1\13\1\56\27\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\1\13\1\265\27\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\17\13\1\56\11\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\2\13\1\266\26\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\14\13\1\267\14\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\20\13\1\56"+
    "\10\13\16\0\2\3\7\0\1\13\1\54\2\0\15\13"+
    "\1\152\13\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\17\13\1\270\11\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\6\13\1\271\22\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\17\13\1\272\11\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\12\13\1\273\16\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\12\13\1\274\16\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\16\13\1\56\12\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\17\13\1\212"+
    "\11\13\16\0\2\3\7\0\1\13\1\54\2\0\10\13"+
    "\1\152\20\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\3\13\1\275\25\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\5\13\1\276\23\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\2\13\1\277\26\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\17\13\1\152\11\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\12\13\1\300\16\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\1\13\1\301\27\13"+
    "\16\0\2\3\7\0\1\13\1\54\2\0\1\13\1\212"+
    "\27\13\16\0\2\3\7\0\1\13\1\54\2\0\25\13"+
    "\1\56\3\13\16\0\2\3\7\0\1\13\1\54\2\0"+
    "\1\13\1\302\27\13\16\0\2\3\7\0\1\13\1\54"+
    "\2\0\12\13\1\170\16\13\16\0\2\3\7\0\1\13"+
    "\1\54\2\0\5\13\1\303\23\13\16\0\2\3\7\0"+
    "\1\13\1\54\2\0\2\13\1\137\26\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\1\304\30\13\16\0\2\3"+
    "\7\0\1\13\1\54\2\0\3\13\1\56\25\13\16\0"+
    "\2\3\7\0\1\13\1\54\2\0\27\13\1\277\1\13"+
    "\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9620];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\37\1\1\11\1\1\6\0"+
    "\45\1\1\0\4\1\2\0\46\1\2\0\1\1\1\0"+
    "\27\1\1\11\1\1\1\0\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 136) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 7: 
          { lexeme=yytext(); return KEYWORD;
          }
        case 10: break;
        case 1: 
          { return ERROR;
          }
        case 11: break;
        case 8: 
          { lexeme=yytext(); return COMENTARIO;
          }
        case 12: break;
        case 2: 
          { lexeme=yytext(); return IDENTIFICADOR;
          }
        case 13: break;
        case 4: 
          { lexeme=yytext(); return SIMBOLOS;
          }
        case 14: break;
        case 9: 
          { lexeme=yytext(); return ARRAY;
          }
        case 15: break;
        case 3: 
          { lexeme=yytext(); return LITERAL;
          }
        case 16: break;
        case 5: 
          { lexeme=yytext(); return OPERADOR;
          }
        case 17: break;
        case 6: 
          { /*Ignore*/
          }
        case 18: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
